/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CatalogPaginator: typeof import('./src/components/products/CatalogPaginator.vue')['default']
    CatalogSearch: typeof import('./src/components/products/CatalogSearch.vue')['default']
    GlobalNavbar: typeof import('./src/components/GlobalNavbar.vue')['default']
    GlobalPaginator: typeof import('./src/components/GlobalPaginator.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    UserDataForm: typeof import('./src/components/users/UserDataForm.vue')['default']
    ViewWrapper: typeof import('./src/components/ViewWrapper.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const CatalogPaginator: typeof import('./src/components/products/CatalogPaginator.vue')['default']
  const CatalogSearch: typeof import('./src/components/products/CatalogSearch.vue')['default']
  const GlobalNavbar: typeof import('./src/components/GlobalNavbar.vue')['default']
  const GlobalPaginator: typeof import('./src/components/GlobalPaginator.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
  const UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  const UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
  const UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
  const UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
  const UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
  const UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  const UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
  const USeparator: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
  const UserDataForm: typeof import('./src/components/users/UserDataForm.vue')['default']
  const ViewWrapper: typeof import('./src/components/ViewWrapper.vue')['default']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}